title: SMART Health Cards
email: your-email@example.com
description: SMART Health Cards Onboarding Documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onboarding.smarthealth.cards" # the base hostname & protocol for your site, e.g. http://example.com
theme: cayman
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
