name: Push File to Prod (test)

on:
  push:
    branches:
      gh-pages

jobs:
  build-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add local changes
      run: |
        git config user.name 'GitHub Bot'
        git config user.email 'sample@email.com'
        git add .
        git commit -m "Update from other repo"

    - name: Save changes
      uses: actions/upload-artifact@v3
      with:
        name: changes
        path: changes

  pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout remote
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: KreigD/smart-health-cards-staging.github.io

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        branch: create-pull-request/br_pull-request
        branch-suffix: timestamp
        delete-branch: true
        title: test pr
        commit-message: Update from other repo