name: broken-link-check

on:
  push: # Trigger the workflow on push
    branches:
      - gh-pages # Push events to gh-pages branch

jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with:
          TARGET: https://smart.kreigd.com

