name: Push File to Prod (test)

on:
  push:
    branches:
      gh-pages

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Save changes
      uses: actions/upload-artifact@v3
      with:
        name: changes
        path: ./
        retention-days: 1

  pull-request:
    needs: build-changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout remote
      uses: actions/checkout@v3
      with:
        token: ${{ env.GITHUB_TOKEN }}
        repository: KreigD/smart-health-cards-staging.github.io
        ref: gh-pages

    - name: Download changes
      uses: actions/download-artifact@v3
      with:
        name: changes
        path: changes

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        cwd: changes

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ env.GITHUB_TOKEN }}
        branch: create-pull-request/br_pull-request
        branch-suffix: timestamp
        delete-branch: true
        title: test pr
        commit-message: Update from other repo