name: Push File to Prod (test)

on:
  push:
    branches:
      gh-pages

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout local
      uses: actions/checkout@v4

    # Create the commit to send to the remote repository
    - name: Create commit
      run: |
        git config --global user.name 'GitHub'
        git config --global user.email '
        git add .
        git commit -m "Update from other repo"
        git push

    - name: Checkout remote
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: builtmighty/smart-health-cards.github.io
        ref: gh-pages

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: gh-pages
        branch: create-pull-request/br_pull-request
        branch-suffix: timestamp
        delete-branch: true
        title: test pr
        commit-message: Update from other repo