name: Push File to Prod (test)

on:
  push:
    branches:
      gh-pages

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      # Repo scope required to create pull requests against the repository
      contents: read
      pull-requests: write
    steps:
    - name: Checkout remote
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: smart-health-cards/smart-health-cards-staging.github.io

    # Make changes to the pull request
    - name: Update pull request
      run: |
        git log -1 --pretty=%B > pull_request.txt

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        branch: create-pull-request/br_pull-request
        branch-suffix: timestamp
        delete-branch: true
        title: test pr
        commit-message: Update from other repo