name: Push File to Prod (test)

on:
  push:
    branches:
      gh-pages

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: builtmighty/smart-health-cards.github.io
        ref: gh-pages

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # base: gh-pages
        branch: create-pull-request/br_pull-request
        delete-branch: true
        title: test pr
        commit-message: Update from https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA
