name: Push File to Prod (test)

on:
  push:
    branches:
      gh-pages


jobs:
  build-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Save changes
      uses: actions/upload-artifact@v3
      with:
        name: changes
        path: ./
        retention-days: 1

  pull-request:
    needs: build-changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout remote
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: KreigD/smart-health-cards-staging.github.io
        ref: gh-pages

    - name: Download changes
      uses: actions/download-artifact@v3
      with:
        name: changes
        path: changes

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "${{ github.event.head_commit.message }}"
        git push
      # uses: EndBug/add-and-commit@v9
      # with:
      #   cwd: changes
      #   default_author: github_actions

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        branch: create-pull-request/br_pull-request
        branch-suffix: timestamp
        delete-branch: true
        title: test pr
        commit-message: Update from other repo