name: Push File to Prod (test)

on:
  push:
    branches:
      gh-pages

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout remote
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: builtmighty/smart-health-cards.github.io

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: create-pull-request/br_pull-request
        branch-suffix: timestamp
        delete-branch: true
        title: test pr
        commit-message: Update from other repo