name: Push File to Prod (test)

on:
  push:
    branches:
      gh-pages

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      # Repo scope required to create pull requests against the repository
      contents: read
      pull-requests: write
    steps:
    - name: Checkout remote
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        repository: KreigD/smart-health-cards-staging.github.io

    # Update the pull request with the local changes
    - name: Update pull request
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git checkout -b create-pull-request/br_pull-request
        git add .
        git commit -m "Update from other repo"
        git push origin create-pull-request/br_pull-request

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        branch: create-pull-request/br_pull-request
        branch-suffix: timestamp
        delete-branch: true
        title: test pr
        commit-message: Update from other repo