name: Push File to Prod (test)

on: push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: car-on-sale/action-pull-request-another-repo@v1.3.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source_folder: '/'
        destination_repo: 'builtmighty/smart-health-cards.github.io'
        destination_folder: '/'
        destination_base_branch: 'gh-pages'
        destination_head_branch: 'br_pull-request'
        user_email: 'kreig.e.durham@gmail.com'
        user_name: 'KreigD'
        pr_title: 'test pr: disregard'
        commit_msg: 'Update from https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA'
